version: '3.5'
services:
  webhook-service:
    build:
      dockerfile: Dockerfile.dev
      context: ./Moleculer-Server
    env_file: ./Moleculer-Server/config/dev.env
    ports:
      - 3001:3001
    depends_on:
      - mongo

  express-backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./Express-Server
    restart: unless-stopped
    env_file:
      - ./Express-Server/src/config/dev.env
    ports:
      - 3000:3000
    depends_on:
      - webhook-service

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  mongo-ui:
    image: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
    ports:
      - 8001:8081
    depends_on:
      - mongo

volumes:
  mongodata:
