version: '3.5'
services:
  express-backend:
    build:
      dockerfile: Dockerfile.dev
      context: .
    restart: always
    env_file:
      - ./src/config/dev.env
    ports:
      - 3000:3000
    volumes:
      # - /usr/app/node_modules
      - .:/usr/app
